--- #YAML:1.0
name:                Tie-Hash-Array
version:             0.1
abstract:            a hash which is internally implemented as a sorted array
license:             ~
author:              
    - Martin H. Sluka <perl@sluka.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Text::Abbrev:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
